maxTrialCount: 8000
parallelTrialCount: 10
studySpec:
  metrics:
  - metricId: ACCURACY
    goal: MAXIMIZE
  parameters:
  - parameterId: learning_rate
    doubleValueSpec:
      minValue: 0.01
      maxValue: 1
  - parameterId: momentum
    doubleValueSpec:
      maxValue: 1
  - parameterId: num_neurons
    discreteValueSpec:
      values:
      - 512
  algorithm: RANDOM_SEARCH
trialJobSpec:
  workerPoolSpecs:
  - machineSpec:
      machineType: g2-standard-32
    replicaCount: '1'
    diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
    containerSpec:
      imageUri: gcr.io/$PROJECT_ID/sule:latest
  - machineSpec:
      machineType: g2-standard-32
    replicaCount: '1'
    diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
    containerSpec:
      imageUri: gcr.io/$PROJECT_ID/sule:latest
